[tool.poetry]
name = "pyrexia"
version = "0.1.0"
description = "Library to read .tsg file package"
authors = ["Ben <ben@fractalgeoanalytics.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.23.1"
tomli = "^2.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
